/** Stripe webhook event types handled (or planned) by GOFOFA. */
export const STRIPE_WEBHOOK_EVENTS = {
  customerCreated: "customer.created",
  customerUpdated: "customer.updated",
  customerDeleted: "customer.deleted",
  checkoutSessionCompleted: "checkout.session.completed",
  paymentMethodAttached: "payment_method.attached",
  paymentMethodDetached: "payment_method.detached",
  paymentMethodAutomaticallyUpdated: "payment_method.automatically_updated",
  invoiceCreated: "invoice.created",
  invoiceUpdated: "invoice.updated",
  invoiceFinalized: "invoice.finalized",
  invoicePaid: "invoice.paid",
  invoicePaymentFailed: "invoice.payment_failed",
  invoiceVoided: "invoice.voided",
  invoiceMarkedUncollectible: "invoice.marked_uncollectible",
  productCreated: "product.created",
  productUpdated: "product.updated",
  productDeleted: "product.deleted",
  priceCreated: "price.created",
  priceUpdated: "price.updated",
  priceDeleted: "price.deleted",
  paymentIntentSucceeded: "payment_intent.succeeded",
  paymentIntentPaymentFailed: "payment_intent.payment_failed",
  paymentIntentCanceled: "payment_intent.canceled",
  chargeSucceeded: "charge.succeeded",
  chargeFailed: "charge.failed",
  chargeRefunded: "charge.refunded",
  chargeDisputeCreated: "charge.dispute.created",
} as const;

export type StripeWebhookEventType =
  (typeof STRIPE_WEBHOOK_EVENTS)[keyof typeof STRIPE_WEBHOOK_EVENTS];

/** Event types to register on the Stripe webhook endpoint (Dashboard or CLI). */
export const STRIPE_WEBHOOK_EVENT_TYPES: StripeWebhookEventType[] = [
  STRIPE_WEBHOOK_EVENTS.customerCreated,
  STRIPE_WEBHOOK_EVENTS.customerUpdated,
  STRIPE_WEBHOOK_EVENTS.customerDeleted,
  STRIPE_WEBHOOK_EVENTS.checkoutSessionCompleted,
  STRIPE_WEBHOOK_EVENTS.paymentMethodAttached,
  STRIPE_WEBHOOK_EVENTS.paymentMethodDetached,
  STRIPE_WEBHOOK_EVENTS.paymentMethodAutomaticallyUpdated,
  STRIPE_WEBHOOK_EVENTS.invoiceCreated,
  STRIPE_WEBHOOK_EVENTS.invoiceUpdated,
  STRIPE_WEBHOOK_EVENTS.invoiceFinalized,
  STRIPE_WEBHOOK_EVENTS.invoicePaid,
  STRIPE_WEBHOOK_EVENTS.invoicePaymentFailed,
  STRIPE_WEBHOOK_EVENTS.invoiceVoided,
  STRIPE_WEBHOOK_EVENTS.invoiceMarkedUncollectible,
  STRIPE_WEBHOOK_EVENTS.productCreated,
  STRIPE_WEBHOOK_EVENTS.productUpdated,
  STRIPE_WEBHOOK_EVENTS.productDeleted,
  STRIPE_WEBHOOK_EVENTS.priceCreated,
  STRIPE_WEBHOOK_EVENTS.priceUpdated,
  STRIPE_WEBHOOK_EVENTS.priceDeleted,
  STRIPE_WEBHOOK_EVENTS.paymentIntentSucceeded,
  STRIPE_WEBHOOK_EVENTS.paymentIntentPaymentFailed,
  STRIPE_WEBHOOK_EVENTS.paymentIntentCanceled,
  STRIPE_WEBHOOK_EVENTS.chargeSucceeded,
  STRIPE_WEBHOOK_EVENTS.chargeFailed,
  STRIPE_WEBHOOK_EVENTS.chargeRefunded,
  STRIPE_WEBHOOK_EVENTS.chargeDisputeCreated,
];
