/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HelpMeChooseRouteImport } from './routes/help-me-choose'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PickupRouteImport } from './routes/pickup'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBatchesRouteImport } from './routes/admin/batches'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminItemsRouteImport } from './routes/admin/items'
import { Route as AdminKitchenRouteImport } from './routes/admin/kitchen'
import { Route as AdminMembershipsRouteImport } from './routes/admin/memberships'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as FeedbackOrderIdRouteImport } from './routes/feedback.$orderId'
import { Route as PlansCategoryIdRouteImport } from './routes/plans.$categoryId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers.index'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin/customers.$customerId'
import { Route as AdminCustomersNewRouteImport } from './routes/admin/customers.new'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as AccountOrdersOrderIdSelectRouteImport } from './routes/account.orders.$orderId.select'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpMeChooseRoute = HelpMeChooseRouteImport.update({
  id: '/help-me-choose',
  path: '/help-me-choose',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupRoute = PickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBatchesRoute = AdminBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackOrderIdRoute = FeedbackOrderIdRouteImport.update({
  id: '/feedback/$orderId',
  path: '/feedback/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansCategoryIdRoute = PlansCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => PlansRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersOrderIdSelectRoute =
  AccountOrdersOrderIdSelectRouteImport.update({
    id: '/select',
    path: '/select',
    getParentRoute: () => AccountOrdersOrderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help-me-choose': typeof HelpMeChooseRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pickup': typeof PickupRoute
  '/plans': typeof PlansRouteWithChildren
  '/review': typeof ReviewRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/items': typeof AdminItemsRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/feedback/$orderId': typeof FeedbackOrderIdRoute
  '/plans/$categoryId': typeof PlansCategoryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRouteWithChildren
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/account/orders/$orderId/select': typeof AccountOrdersOrderIdSelectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help-me-choose': typeof HelpMeChooseRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pickup': typeof PickupRoute
  '/plans': typeof PlansRouteWithChildren
  '/review': typeof ReviewRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/feedback/$orderId': typeof FeedbackOrderIdRoute
  '/plans/$categoryId': typeof PlansCategoryIdRoute
  '/admin': typeof AdminIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRouteWithChildren
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/account/orders/$orderId/select': typeof AccountOrdersOrderIdSelectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help-me-choose': typeof HelpMeChooseRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pickup': typeof PickupRoute
  '/plans': typeof PlansRouteWithChildren
  '/review': typeof ReviewRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/items': typeof AdminItemsRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/feedback/$orderId': typeof FeedbackOrderIdRoute
  '/plans/$categoryId': typeof PlansCategoryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRouteWithChildren
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/account/orders/$orderId/select': typeof AccountOrdersOrderIdSelectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/cart'
    | '/confirmation'
    | '/contact'
    | '/faq'
    | '/help-me-choose'
    | '/locations'
    | '/login'
    | '/pickup'
    | '/plans'
    | '/review'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/batches'
    | '/admin/customers'
    | '/admin/items'
    | '/admin/kitchen'
    | '/admin/memberships'
    | '/admin/orders'
    | '/admin/settings'
    | '/api/health'
    | '/feedback/$orderId'
    | '/plans/$categoryId'
    | '/admin/'
    | '/account/orders/$orderId'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/api/stripe/webhook'
    | '/admin/customers/'
    | '/account/orders/$orderId/select'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/confirmation'
    | '/contact'
    | '/faq'
    | '/help-me-choose'
    | '/locations'
    | '/login'
    | '/pickup'
    | '/plans'
    | '/review'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/batches'
    | '/admin/items'
    | '/admin/kitchen'
    | '/admin/memberships'
    | '/admin/orders'
    | '/admin/settings'
    | '/api/health'
    | '/feedback/$orderId'
    | '/plans/$categoryId'
    | '/admin'
    | '/account/orders/$orderId'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/api/stripe/webhook'
    | '/admin/customers'
    | '/account/orders/$orderId/select'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/cart'
    | '/confirmation'
    | '/contact'
    | '/faq'
    | '/help-me-choose'
    | '/locations'
    | '/login'
    | '/pickup'
    | '/plans'
    | '/review'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/batches'
    | '/admin/customers'
    | '/admin/items'
    | '/admin/kitchen'
    | '/admin/memberships'
    | '/admin/orders'
    | '/admin/settings'
    | '/api/health'
    | '/feedback/$orderId'
    | '/plans/$categoryId'
    | '/admin/'
    | '/account/orders/$orderId'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/api/stripe/webhook'
    | '/admin/customers/'
    | '/account/orders/$orderId/select'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HelpMeChooseRoute: typeof HelpMeChooseRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  PickupRoute: typeof PickupRoute
  PlansRoute: typeof PlansRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  FeedbackOrderIdRoute: typeof FeedbackOrderIdRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-me-choose': {
      id: '/help-me-choose'
      path: '/help-me-choose'
      fullPath: '/help-me-choose'
      preLoaderRoute: typeof HelpMeChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup': {
      id: '/pickup'
      path: '/pickup'
      fullPath: '/pickup'
      preLoaderRoute: typeof PickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/batches': {
      id: '/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kitchen': {
      id: '/admin/kitchen'
      path: '/kitchen'
      fullPath: '/admin/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$orderId': {
      id: '/feedback/$orderId'
      path: '/feedback/$orderId'
      fullPath: '/feedback/$orderId'
      preLoaderRoute: typeof FeedbackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$categoryId': {
      id: '/plans/$categoryId'
      path: '/$categoryId'
      fullPath: '/plans/$categoryId'
      preLoaderRoute: typeof PlansCategoryIdRouteImport
      parentRoute: typeof PlansRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/new': {
      id: '/admin/customers/new'
      path: '/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$orderId/select': {
      id: '/account/orders/$orderId/select'
      path: '/select'
      fullPath: '/account/orders/$orderId/select'
      preLoaderRoute: typeof AccountOrdersOrderIdSelectRouteImport
      parentRoute: typeof AccountOrdersOrderIdRoute
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  AdminCustomersNewRoute: AdminCustomersNewRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBatchesRoute: typeof AdminBatchesRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminItemsRoute: typeof AdminItemsRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBatchesRoute: AdminBatchesRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminItemsRoute: AdminItemsRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AccountOrdersOrderIdRouteChildren {
  AccountOrdersOrderIdSelectRoute: typeof AccountOrdersOrderIdSelectRoute
}

const AccountOrdersOrderIdRouteChildren: AccountOrdersOrderIdRouteChildren = {
  AccountOrdersOrderIdSelectRoute: AccountOrdersOrderIdSelectRoute,
}

const AccountOrdersOrderIdRouteWithChildren =
  AccountOrdersOrderIdRoute._addFileChildren(AccountOrdersOrderIdRouteChildren)

interface AccountRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRouteWithChildren
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRouteWithChildren,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface PlansRouteChildren {
  PlansCategoryIdRoute: typeof PlansCategoryIdRoute
}

const PlansRouteChildren: PlansRouteChildren = {
  PlansCategoryIdRoute: PlansCategoryIdRoute,
}

const PlansRouteWithChildren = PlansRoute._addFileChildren(PlansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HelpMeChooseRoute: HelpMeChooseRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  PickupRoute: PickupRoute,
  PlansRoute: PlansRouteWithChildren,
  ReviewRoute: ReviewRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  FeedbackOrderIdRoute: FeedbackOrderIdRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
